<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sies PWA</title>
    <link rel="stylesheet" href="CSS/estilos.css">
</head>
<body>
    <header>
        <nav>
            <a href="#">Inicio</a>
            <a href="PDF/Propuesta_Solucion.pdf">Plan del Proyecto</a>
            <a href="PDF/Plan_Proyecto.pdf">Propuesta de Solución</a>
        </nav>
        <section class="textos-header">
            <h1>Sies PWA</h1>
        </section>
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
            style="height: 100%; width: 100%;">
            <path d="M0.00,49.98 C150.00,150.00 349.20,-50.00 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
                style="stroke: none; fill: #fff;"></path>
        </svg></div>
    
    </header>
    <main>
        <section class="contenedor sobre-nosotros">
            <h2 class="titulo">Objetivos</h2>
            <div class="contenedor-sobre-nosotros">
                <img src="img/ilustracion2.svg" alt="" class="imagen-about-us">
                <div class="contenido-textos">
                    <h3><span>1</span>Tener una aplicación web, compatible en todos los SO.</h3>
                    <h3><span>2</span>Poder recibir notificaciones cuando algún profesor suba calificación.</h3>
                    <h3><span>3</span>De facil instalación.</h3>
                    <h3><span>4</span>No recargar datos innecesarios.</h3>
                    <h3><span>5</span>Datos seguros.</h3>
                    <h3><span>6</span>Aspecto visual detallado.</h3>
                </div>
            </div>
        </section>
        <section>
            <h2 class="titulo">Video</h2>
            <div style="text-align: center;">
                <iframe width="560" height="315" src="https://www.youtube.com/embed/bNP0nbYo0jE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </section>
        <section>
            <h2 class="titulo">Presentación</h2>
            <div style="text-align: center;">
                    <iframe src="https://onedrive.live.com/embed?cid=5E3BEA1D89BF0E9A&amp;resid=5e3bea1d89bf0e9a%213520&amp;authkey=AD-PnONV0nWwwqw&amp;em=2&amp;wdAr=1.7777777777777777" width="610px" height="367px" frameborder="0">Esto es un documento de <a target="_blank" href="https://office.com">Microsoft Office</a> incrustado con tecnología de <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>
            </div>
        </section>
        <section class="portafolio">
            <div class="contenedor">
                <h2 class="titulo">Contenido</h2>
                <div class="galeria-port">
                    <div class="imagen-port">
                        <img src="img/index.png" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                            <p>Index</p>
                        </div>
                    </div>
                    <div class="imagen-port">
                        <img src="img/home.png" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                            <p>Home</p>
                        </div>
                    </div>
                    <div class="imagen-port">
                        <img src="img/insert_calificaciones.png" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                            <p>Insertar</p>
                        </div>
                    </div>
                    <div class="imagen-port">
                        <img src="img/view_Reporte.png" alt="">
                        <div class="hover-galeria">
                            <img src="img/icono1.png" alt="">
                            <p>View</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="clientes contenedor">
            <h2 class="titulo">Puntos Fuertes</h2>
            <div class="cards">
                <div class="card">
                    <div class="contenido-texto-card">
                        <h4>Notificaciones</h4>
                        <p>Cuando algún profesor suba o haga una modificación de alguna calificación, al usuario le llegará una notificación para que pueda revisar.</p>
                    </div>
                </div>
                <div class="card">
                    <div class="contenido-texto-card">
                        <h4>Instalación</h4>
                        <p>Fácil de instalar y tener siempre cerca para su rápido acceso</p>
                    </div>
                </div>
                <div class="card">
                    <div class="contenido-texto-card">
                        <h4>Conexion a Internet</h4>
                        <p>No necesita conexión a internet, con esto podemos ver nuestras calificaciones ya antes subidas sin la necesidad de tener datos móviles.</p>
                    </div>
                </div>
            </div>
        </section>
    </main>
</body>
</html>